### ISSUE TITLE
Discount amounts multiplied when same item in cart multiple times

### ISSUE THREAD

**Issue by SDavisMedia** [easydigitaldownloads/edd-discounts-pro#114]
It's easier to show this in action first. Here's an example setup to replicate the issue.

Configure a discount like so:

<img width="506" alt="screenshot 2017-01-16 10 34 36" src="https://cloud.githubusercontent.com/assets/2359131/21995000/70d14dca-dbd7-11e6-9a02-95def06499af.png">

Now add a product to the cart 3 or more times. Note that you are adding _the same_ product to the cart to trigger the discount. Here's what you end up with:

<img width="723" alt="screenshot 2017-01-16 10 36 57" src="https://cloud.githubusercontent.com/assets/2359131/21995061/b9600fd6-dbd7-11e6-9316-fcae95878988.png">

-----

In this particular case, you can see that the cart total is discounted by $90. Break that down to be $30 x 3. What we actually have here is all 3 cart items triggering 3 $10 negative fees. 

That's the bug, mane.

**Comment by brashrebel** [comment]
I've got [another customer](https://secure.helpscout.net/conversation/397963330/63143/) experiencing this problem. Products in Cart discount with multiples of the same item in the cart results in not-even-close-to-correct cart totals.

**Comment by pippinsplugins** [comment]
Tagging for next point release.

**Comment by pippinsplugins** [comment]
Ok I've taken a stab at fixing this and believe I have a working solution.

Could I please get some testing on it?

Please test other discount types too.

**Comment by pippinsplugins** [comment]
This is the relevant commit: https://github.com/easydigitaldownloads/edd-discounts-pro/pull/132/commits/ad6eec7445282689666e6628352bd101dc9fc0cd - Everything else is just formatting.

**Comment by SDavisMedia** [comment]
@pippinsplugins Yup this appears to fix it. I checked all the other discount types and bounced their behavior off of `master`. Wherever I could replicate on `master`, `issue/114` fixed it. :+1:
