### ISSUE TITLE
Taxes still included on checkout with 100% discount

### ISSUE THREAD

**Issue by brashrebel** [easydigitaldownloads/edd-discounts-pro#115]
When attempting to checkout, if taxes are enabled and are inclusive of tax, _and_ the customer enters an address which matches a configured tax rate, _and_ the cart includes an item with a 100% discount, taxes will still be included in the purchase amount when they should really be zero.
![Screen Shot 2017-02-09 at 5.37.02 PM](http://static.gitscout.com/b40fc24815e1f1233b3092abdd5aa4d0228ae5c2546a9402547778ba478227bf.png)
![Screen Shot 2017-02-09 at 5.40.17 PM](http://static.gitscout.com/44a09301e2535da645ef1c13a2dd89ea454aa9c2a90ffb81624b56c5eed2a31b.png)
![Screen Shot 2017-02-09 at 5.41.00 PM](http://static.gitscout.com/39059a6856ba39b0a051d4fbc8fc54516848b3ed8dc783c25af022782477df9b.png)

**Comment by cklosowski** [comment]
Looks like we've made a little progress here @brashrebel mind looking to see if you're seeing the same thing I am right now with EDD Master?
![screen shot 2017-05-04 at 5 08 46 pm](https://cloud.githubusercontent.com/assets/1390124/25729769/66ee4c08-30ec-11e7-8e89-63ab388b210d.png)

**Comment by cklosowski** [comment]
We should have that discount actually account for the price inclusive of tax...so that it's zero'd out.

**Comment by cklosowski** [comment]
Ok I think I have this working as far as Discounts Pro is concerend, but I think that there is an EDD Core bug here, that tax is being calculated even when the items in the cart and the discount fees equal `0`

![screen shot 2017-05-05 at 9 15 15 am](https://cloud.githubusercontent.com/assets/1390124/25754264/7157c1c4-3173-11e7-93c0-028712ee8060.png)

**Comment by cklosowski** [comment]
The above brings it to a $0.00 cart, and therefore doesn't take in any payment information, so it still works, just looks a little funky, which we can fix in core I believe.

**Comment by cklosowski** [comment]
I've submitted the EDD core fix here: https://github.com/easydigitaldownloads/easy-digital-downloads/issues/5709

**Comment by cklosowski** [comment]
@brashrebel mind testing this out for me extensively?

**Comment by cklosowski** [comment]
For testing please try the following combinations:
1) Prices Exclusive of tax & Cart prices inclusive of tax
2) Prices Exclusive of tax & Cart Prices exclusive of tax 
3) Prices inclusive of tax & Cart prices inclusive of tax
4) Prices inclusive of tax & cart prices exclusive of tax

Those are the settings in the Tax area of EDD.

**Comment by pippinsplugins** [comment]
Note, to fully test this, you also need to be on the latest `release/2.8` branch of core for https://github.com/easydigitaldownloads/easy-digital-downloads/issues/5709

**Comment by pippinsplugins** [comment]
Here's one that's odd: Prices exclusive of tax and checkout prices shown with tax:
<img width="683" alt="screen shot 2017-05-05 at 1 56 42 pm" src="https://cloud.githubusercontent.com/assets/1034109/25760085/bc072152-319a-11e7-9074-336384e2b126.png">

<img width="1810" alt="screen shot 2017-05-05 at 1 57 17 pm" src="https://cloud.githubusercontent.com/assets/1034109/25760094/c79affca-319a-11e7-816e-52ad2e63f912.png">

The discount is 100% but the discount amount shown on checkout is 0.25 less than the item.

**Comment by pippinsplugins** [comment]
Similar behavior happens when prices are inclusive of tax and prices are shown with tax on checkout:

<img width="1780" alt="screen shot 2017-05-05 at 1 58 38 pm" src="https://cloud.githubusercontent.com/assets/1034109/25760129/f4c333dc-319a-11e7-9bed-f1583870bda4.png">
<img width="669" alt="screen shot 2017-05-05 at 1 58 11 pm" src="https://cloud.githubusercontent.com/assets/1034109/25760131/f6453976-319a-11e7-8edd-b1a8aaabadf5.png">

**Comment by pippinsplugins** [comment]
Ignore that! I was on the wrong branch.

Switching to `issue/115` makes all scenarios work as expected!

**Comment by SDavisMedia** [comment]
All good here. :+1:
