### ISSUE TITLE
Incorrect tax amount when discount applied.

### ISSUE THREAD

**Issue by mintplugins** [easydigitaldownloads/edd-discounts-pro#128]
Take the following scenario:

Product A costs 100 and is in the cart 3 times = $300

Discounts pro applied a 50% discount because of cart quantity. 

Cart Subtotal is $150

The tax is still being charged on the $300 instead of the $150. 

<img width="552" alt="screen shot 2017-07-14 at 2 47 06 pm" src="https://user-images.githubusercontent.com/1638128/28226652-ef3f2d62-68a4-11e7-95fe-24f213c8055b.png">

A customer reported this here:
https://secure.helpscout.net/conversation/396107699/62816/?folderId=180504

I replicated it myself.

**Comment by pippinsplugins** [comment]
I'm fairly certain this is actually a core bug. Investigating.

**Comment by pippinsplugins** [comment]
Another report https://secure.helpscout.net/conversation/411514486/64611/?folderId=180499

**Comment by pippinsplugins** [comment]
It is indeed a core bug. Issue and PR created: https://github.com/easydigitaldownloads/easy-digital-downloads/issues/5940
