### ISSUE TITLE
Ability to offer buy one, get x% off discounts

### ISSUE THREAD

**Issue by Chaddeus** [easydigitaldownloads/edd-discounts-pro#137]
There doesn't seem to be a way to let a user add more than one of a product to the cart, and offer discounts on the items beyond the first. Like the classic, buy one get one x% off scenario. 

Am I just missing some combination of settings?

**Comment by chriscct7** [comment]
Discounts Pro already offers this. You can discount each x product (ex every third product) by flat rate or percent, each product after x number in cart, or by the quantity of a specific product in the cart.

You're probably looking for the each x products discount type in EDD

Bare in mind if you want to do discounts on product quantities you need to turn them on in Edd core.
